
import __ASTRO_IMAGE_IMPORT_Z1dEHuv from "./brand.png?astroContentImageFlag=&importer=src%2Fcontent%2Ffeatured-case-studies%2Feasy-jet%2Findex.md";
import __ASTRO_IMAGE_IMPORT_1CTWQR from "./brand.png?astroContentImageFlag=&importer=src%2Fcontent%2Ffeatured-case-studies%2Fuefa%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z1VxXfO from "./brand.png?astroContentImageFlag=&importer=src%2Fcontent%2Ffeatured-case-studies%2Fsony%2Findex.md";
import __ASTRO_IMAGE_IMPORT_ZL3paK from "./brand.png?astroContentImageFlag=&importer=src%2Fcontent%2Ffeatured-case-studies%2Fbbc%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z1YybMd from "./award.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Faqr-award-shortlisting-2021%2Findex.md";
import __ASTRO_IMAGE_IMPORT_2tHjda from "./brand.png?astroContentImageFlag=&importer=src%2Fcontent%2Ffeatured-case-studies%2Fvirgin-pure%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Lomub from "./brand.png?astroContentImageFlag=&importer=src%2Fcontent%2Ffeatured-case-studies%2Fset-app%2Findex.md";
import __ASTRO_IMAGE_IMPORT_nnyjU from "./painpoints.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fwhat-does-agile-online-qualitative-research-mean%2Findex.md";
import __ASTRO_IMAGE_IMPORT_equnB from "./logo.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhow-mobile-qualitative-research-inspired-swingers-global-expansion%2Findex.md";
import __ASTRO_IMAGE_IMPORT_23dho6 from "./tom.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fwhy-are-we-called-feeling-mutual%2Findex.md";
import __ASTRO_IMAGE_IMPORT_2dwdl0 from "./award.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmrs-independent-researchers-award-winner-2021%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z2mv1Jn from "./authentic.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fwhat-makes-online-qual-more-authentic-than-traditional-methods%2Findex.md";
import __ASTRO_IMAGE_IMPORT_2gBJsi from "./award.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmrs-award-nomination-2017%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z2epwfq from "./award.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fquirks-market-research-excellence-award-winner-2020%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z3dMpn from "./puzzle.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fwhat-is-best-practice-when-hiring-freelance-researchers%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z2uV0Gl from "./award.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmrs-award-nomination-2019%2Findex.md";
export default new Map([["./brand.png?astroContentImageFlag=&importer=src%2Fcontent%2Ffeatured-case-studies%2Feasy-jet%2Findex.md", __ASTRO_IMAGE_IMPORT_Z1dEHuv], ["./brand.png?astroContentImageFlag=&importer=src%2Fcontent%2Ffeatured-case-studies%2Fuefa%2Findex.md", __ASTRO_IMAGE_IMPORT_1CTWQR], ["./brand.png?astroContentImageFlag=&importer=src%2Fcontent%2Ffeatured-case-studies%2Fsony%2Findex.md", __ASTRO_IMAGE_IMPORT_Z1VxXfO], ["./brand.png?astroContentImageFlag=&importer=src%2Fcontent%2Ffeatured-case-studies%2Fbbc%2Findex.md", __ASTRO_IMAGE_IMPORT_ZL3paK], ["./award.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Faqr-award-shortlisting-2021%2Findex.md", __ASTRO_IMAGE_IMPORT_Z1YybMd], ["./brand.png?astroContentImageFlag=&importer=src%2Fcontent%2Ffeatured-case-studies%2Fvirgin-pure%2Findex.md", __ASTRO_IMAGE_IMPORT_2tHjda], ["./brand.png?astroContentImageFlag=&importer=src%2Fcontent%2Ffeatured-case-studies%2Fset-app%2Findex.md", __ASTRO_IMAGE_IMPORT_Lomub], ["./painpoints.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fwhat-does-agile-online-qualitative-research-mean%2Findex.md", __ASTRO_IMAGE_IMPORT_nnyjU], ["./logo.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhow-mobile-qualitative-research-inspired-swingers-global-expansion%2Findex.md", __ASTRO_IMAGE_IMPORT_equnB], ["./tom.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fwhy-are-we-called-feeling-mutual%2Findex.md", __ASTRO_IMAGE_IMPORT_23dho6], ["./award.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmrs-independent-researchers-award-winner-2021%2Findex.md", __ASTRO_IMAGE_IMPORT_2dwdl0], ["./authentic.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fwhat-makes-online-qual-more-authentic-than-traditional-methods%2Findex.md", __ASTRO_IMAGE_IMPORT_Z2mv1Jn], ["./award.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmrs-award-nomination-2017%2Findex.md", __ASTRO_IMAGE_IMPORT_2gBJsi], ["./award.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fquirks-market-research-excellence-award-winner-2020%2Findex.md", __ASTRO_IMAGE_IMPORT_Z2epwfq], ["./puzzle.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fwhat-is-best-practice-when-hiring-freelance-researchers%2Findex.md", __ASTRO_IMAGE_IMPORT_Z3dMpn], ["./award.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmrs-award-nomination-2019%2Findex.md", __ASTRO_IMAGE_IMPORT_Z2uV0Gl]]);
		